/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

import { taskFetch } from "../../fetch/taskFetch";
import type { ErrorResponse, HealthStatus } from ".././schemas";

/**
 * @summary Get application health status
 */
export type healthGetHealthResponse200 = {
  data: HealthStatus;
  status: 200;
};

export type healthGetHealthResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type healthGetHealthResponse503 = {
  data: HealthStatus;
  status: 503;
};

export type healthGetHealthResponseComposite =
  | healthGetHealthResponse200
  | healthGetHealthResponse500
  | healthGetHealthResponse503;

export type healthGetHealthResponse = healthGetHealthResponseComposite & {
  headers: Headers;
};

export const getHealthGetHealthUrl = () => {
  return `/health`;
};

export const healthGetHealth = async (
  options?: RequestInit,
): Promise<healthGetHealthResponse> => {
  return taskFetch<healthGetHealthResponse>(getHealthGetHealthUrl(), {
    ...options,
    method: "GET",
  });
};
