/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ToDoUser API
 * TodoアプリバックエンドのUserと認証に関するAPI
 * OpenAPI spec version: v0.0.1
 */

export interface SignUpDto {
	/**
	 * @minLength 0
	 * @maxLength 255
	 * @pattern [a-zA-Z0-9]+
	 */
	username: string;
	/** @minLength 1 */
	password: string;
}
