/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ToDoUser API
 * TodoアプリバックエンドのUserと認証に関するAPI
 * OpenAPI spec version: v0.0.1-26-g2b5d421.dirty
 */
import type { SignInJson400ErrorsItem } from "./signInJson400ErrorsItem";

/**
 * RFC 7808 Problem Details with validation errors extension
 */
export type SignInJson400 = {
  /** 問題の種類を識別するURI */
  type?: string;
  /** 問題の概要 */
  title?: string;
  /** HTTPステータスコード */
  status?: number;
  /** 問題の詳細説明 */
  detail?: string;
  /** 問題が発生したリクエストのURI */
  instance?: string;
  /** バリデーションエラーの詳細リスト */
  errors?: SignInJson400ErrorsItem[];
};
