/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ToDoUser API
 * TodoアプリバックエンドのUserと認証に関するAPI
 * OpenAPI spec version: v0.0.1-26-g2b5d421.dirty
 */

export type SignInJson401ErrorsItem = {
	/** エラーが発生したフィールド名 */
	field: string;
	/**
	 * エラーメッセージ
	 * @nullable
	 */
	message?: string | null;
	/**
	 * 拒否された値
	 * @nullable
	 */
	rejectedValue?: string | null;
};
