/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ToDoUser API
 * TodoアプリバックエンドのUserと認証に関するAPI
 * OpenAPI spec version: v0.0.1-26-g2b5d421.dirty
 */

/**
 * ユーザーの詳細な情報
ログインしているユーザー自身の情報
 */
export interface UserDetail {
	username: string;
	userId: string;
	createdAt: string;
}
