/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorResponse {
  /** Error code */
  code: number;
  /** Error message */
  message: string;
  /** Additional error details */
  details?: string;
}
