/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

import type { HealthComponentDetails } from "./healthComponentDetails";
import type { HealthComponentStatus } from "./healthComponentStatus";

export interface HealthComponent {
	/** Component health status */
	status: HealthComponentStatus;
	/** Additional component details */
	details?: HealthComponentDetails;
}
