/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Component health status
 */
export type HealthComponentStatus =
  (typeof HealthComponentStatus)[keyof typeof HealthComponentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthComponentStatus = {
  UP: "UP",
  DOWN: "DOWN",
} as const;
