/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

import type { HealthStatusComponents } from "./healthStatusComponents";
import type { HealthStatusStatus } from "./healthStatusStatus";

export interface HealthStatus {
	/** Overall application health status */
	status: HealthStatusStatus;
	/** Timestamp of the health check */
	timestamp: string;
	/** Health status of individual components */
	components: HealthStatusComponents;
}
