/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Additional component details
 */
export type HealthComponentDetails = { [key: string]: unknown };
