/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthComponent } from "./healthComponent";

/**
 * Health status of individual components
 */
export type HealthStatusComponents = {
	database?: HealthComponent;
};
