/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Server API
 * Task Server API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Overall application health status
 */
export type HealthStatusStatus =
  (typeof HealthStatusStatus)[keyof typeof HealthStatusStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthStatusStatus = {
  UP: "UP",
  DOWN: "DOWN",
} as const;
