/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ToDoUser API
 * TodoアプリバックエンドのUserと認証に関するAPI
 * OpenAPI spec version: v0.0.1-26-g2b5d421.dirty
 */
import { userFetch } from "../../fetch/userFetch";

/**
 * RFC7517
 * @summary JWKsエンドポイント
 */
export type jwksResponseDefault = {
  data: unknown;
  status: number;
};

export type jwksResponseComposite = jwksResponseDefault;

export type jwksResponse = jwksResponseComposite & {
  headers: Headers;
};

export const getJwksUrl = () => {
  return `/.well-known/jwks.json`;
};

export const jwks = async (options?: RequestInit): Promise<jwksResponse> => {
  return userFetch<jwksResponse>(getJwksUrl(), {
    ...options,
    method: "GET",
  });
};
