/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ToDoUser API
 * TodoアプリバックエンドのUserと認証に関するAPI
 * OpenAPI spec version: v0.0.1-26-g2b5d421.dirty
 */
import { delay, HttpResponse, http } from "msw";

export const getJwksMockHandler = (
	overrideResponse?:
		| unknown
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<unknown> | unknown),
) => {
	return http.get("*/.well-known/jwks.json", async (info) => {
		await delay(1000);
		if (typeof overrideResponse === "function") {
			await overrideResponse(info);
		}
		return new HttpResponse(null, { status: 200 });
	});
};
export const getJwksControllerMock = () => [getJwksMockHandler()];
